#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 9
#define PERMISSIVE_HOLD
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define COMBO_TERM 40
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define USB_SUSPEND_WAKEUP_DELAY 2000
