VIA_ENABLE = yes
LTO_ENABLE = yes
ENCODER_MAP_ENABLE = no
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes
RGB_MATRIX_MAXIMUM_BRIGHTNESS = 115
CAPS_WORD_ENABLE = yes
SERIAL_DRIVER = vendor

SRC += oneshot.c
SRC += swapper.c
