#include QMK_KEYBOARD_H

#include "oneshot.h"
#include "swapper.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define LA_SYM MO(SYM)
#define LA_NAV MO(NAV)

// Base layer home row mods
#define C_MTLAW MT(MOD_LALT,KC_W)
#define C_MTLGF MT(MOD_LGUI,KC_F)
#define C_MTLCP MT(MOD_LCTL,KC_P)
#define C_MTRCL MT(MOD_RCTL,KC_L)
#define C_MTRGU MT(MOD_RGUI,KC_U)
#define C_MTLAY MT(MOD_LALT,KC_Y)

#define C_MTLAR MT(MOD_LALT,KC_R)
#define C_MTLSS MT(MOD_LSFT,KC_S)
#define C_MTLCT MT(MOD_LCTL,KC_T)
#define C_MTRCN MT(MOD_RCTL,KC_N)
#define C_MTRSE MT(MOD_RSFT,KC_E)
#define C_MTLAI MT(MOD_LALT,KC_I)

// Game layer home row mods
#define C_MTRCJ MT(MOD_RCTL,KC_J)
#define C_MTRSK MT(MOD_RSFT,KC_K)
#define C_MTLAL MT(MOD_LALT,KC_L)

// Symbol layer
#define C_MTRC5 MT(MOD_RCTL,KC_P5)
#define C_MTRS6 MT(MOD_RSFT,KC_P6)
#define CTLLEFT C(KC_LEFT)
#define CTLRGHT C(KC_RIGHT)

// Nav layer home row mods
#define C_MTCMN MT(MOD_RCTL,KC_MNXT)
#define C_MTCVU MT(MOD_RSFT,KC_VOLU)

#define TAB_L G(KC_TAB)
#define TAB_R G(S(KC_TAB))


enum layers {
    DEF,
    GA1,
    GA2,
    SYM,
    NAV,
    NUM,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[DEF] = LAYOUT(
        QK_GESC, KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,                   KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_BSPC,
        KC_TAB,  KC_Q   , C_MTLAW, C_MTLGF, C_MTLCP, KC_B   ,                   KC_J   , C_MTRCL, C_MTRGU, C_MTLAY, KC_SCLN, KC_DEL ,
        _______, KC_A   , KC_R   , KC_S   , KC_T   , KC_G   ,                   KC_M   , KC_N   , KC_E   , KC_I   , KC_O   , KC_QUOT,
        DF(GA1), KC_Z   , KC_X   , KC_C   , KC_D   , KC_V   , _______, _______, KC_K   , KC_H   , KC_COMM, KC_DOT , KC_SLSH, _______,
                                            KC_LSFT, MO(NAV), KC_ENT , KC_SPC , MO(SYM), KC_RALT
    ),
	[GA1] = LAYOUT(
        KC_ESC , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,                   KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_BSPC,
        KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   ,                   KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_DEL ,
        KC_LSFT, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   ,                   KC_H   , C_MTRCJ, C_MTRSK, C_MTLAL, KC_SCLN, KC_QUOT,
        KC_LCTL, KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   , MO(GA2), _______, KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, DF(DEF),
                                            KC_LGUI, KC_LALT, KC_ENT , KC_SPC , MO(NAV), KC_RALT
    ),
	[GA2] = LAYOUT(
        KC_ESC , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,                   KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_BSPC,
        KC_TAB , KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   ,                   KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_DEL ,
        KC_LSFT, KC_H   , KC_J   , KC_K   , KC_L   , KC_G   ,                   KC_H   , C_MTRCJ, C_MTRSK, C_MTLAL, KC_SCLN, KC_QUOT, 
        KC_LCTL, KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, _______, _______ ,KC_N   , KC_M   , KC_COMM, KC_DOT,  KC_SLSH, DF(DEF), 
                                            KC_LGUI, KC_LALT, KC_ENT , KC_SPC , MO(NAV), KC_RALT
    ),
    [SYM] = LAYOUT(
        KC_GRV , S(KC_1), S(KC_2), S(KC_3), S(KC_4), S(KC_5),                   S(KC_6), S(KC_7), S(KC_8), S(KC_9), S(KC_0), KC_BSPC, 
        KC_TAB , KC_QUOT, KC_LABK, KC_RABK, KC_DQUO, KC_DOT ,                   KC_AMPR, _______, KC_LPRN, KC_RPRN, KC_PERC, KC_DEL ,
        _______, KC_EXLM, KC_MINS, KC_PLUS, KC_EQL , KC_HASH,                   KC_PIPE, KC_COLN, KC_LBRC, KC_RBRC, KC_QUES, _______,
        _______, KC_CIRC, KC_SLSH, KC_ASTR, KC_BSLS, _______, _______, _______, KC_TILD, KC_DLR , KC_LCBR, KC_RCBR, KC_UNDS, _______,
                                            KC_LSFT, _______, _______, _______, _______, _______
    ),
	[NAV] = LAYOUT(
        KC_F12 , KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  ,                   KC_F6  , KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 ,
        _______, KC_HOME, CTLLEFT, KC_UP  , CTLRGHT ,KC_END ,                   _______, KC_RCTL, KC_RGUI, KC_LALT, KC_PSCR, EE_CLR , 
        _______, _______, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGUP,                   KC_MPRV, KC_MNXT, KC_VOLU, _______, _______, QK_BOOT, 
        _______, _______, _______, _______, _______, KC_PGDN, _______, _______, KC_MSTP, KC_MPLY, KC_VOLD, _______, _______, RGB_TOG, 
                                            _______, _______, _______, _______, _______, KC_RSFT
    ),
	[NUM] = LAYOUT(
        _______, _______, _______, _______, _______, _______,                   _______, _______, _______, _______, _______, _______, 
        _______, _______, _______, _______, _______, _______,                   _______, _______, _______, _______, _______, _______, 
        _______, _______, _______, _______, _______, _______,                   _______, _______, _______, _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, TO(DEF)  , 
                                            _______, _______, _______, _______, _______, _______
    )
};

bool is_oneshot_cancel_key(uint16_t keycode) {
    switch (keycode) {
    case LA_SYM:
    case LA_NAV:
        return true;
    default:
        return false;
    }
}

layer_state_t layer_state_set_user(layer_state_t state) {
   return update_tri_layer_state(state, SYM, NAV, NUM);
}

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




