#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Base layer home row mods
#define C_MTLAR MT(MOD_LALT,KC_R)
#define C_MTLSS MT(MOD_LSFT,KC_S)
#define C_MTLCT MT(MOD_LCTL,KC_T)
#define C_MTRCN MT(MOD_RCTL,KC_N)
#define C_MTRSE MT(MOD_RSFT,KC_E)
#define C_MTLAI MT(MOD_LALT,KC_I)

// Game layer home row mods
#define C_MTRCJ MT(MOD_RCTL,KC_J)
#define C_MTRSK MT(MOD_RSFT,KC_K)
#define C_MTLAL MT(MOD_LALT,KC_L)

// Symbol layer
#define C_LSGR LSFT(KC_GRV)

#define C_MTRC5 MT(MOD_RCTL,KC_P5)
#define C_MTRS6 MT(MOD_RSFT,KC_P6)

// Nav layer home row mods
#define C_MTCMN MT(MOD_RCTL,KC_MNXT)
#define C_MTCVU MT(MOD_RSFT,KC_VOLU)

enum layers {
    DEF,
    GAME1,
    GAME2,
    SYM,
    NAV,
    NUM,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_DEF] = LAYOUT(
        QK_GESC, KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,                   KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_BSPC,
        KC_TAB,  KC_Q   , KC_W   , KC_F   , KC_P   , KC_B   ,                   KC_J   , KC_L   , KC_U   , KC_Y   , KC_SCLN, KC_DEL ,
        _______, KC_A   , C_MTLAR, C_MTLSS, C_MTLCT, KC_G   ,                   KC_M   , C_MTRCN, C_MTRSE, C_MTLAI, KC_O   , KC_QUOT,
        TO(1),   KC_Z   , KC_X   , KC_C   , KC_D   , KC_V   , _______, _______, KC_K   , KC_H   , KC_COMM, KC_DOT,  KC_SLSH, _______,
                                            KC_LGUI, MO(3)  , KC_ENT , KC_SPC , MO(4)  , KC_RALT
    ),
	[GAME1] = LAYOUT(
        KC_ESC , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,                   KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_BSPC,
        KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   ,                   KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_DEL ,
        KC_LSFT, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   ,                   KC_H   , C_MTRCJ, C_MTRSK, C_MTLAL, KC_SCLN, KC_QUOT,
        KC_LCTL, KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   , MO(2)  , KC_END , KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, TO(0)  ,
                                            KC_LGUI, KC_LALT, KC_ENT , KC_SPC , MO(3)  , KC_RALT
    ),
	[GAME2] = LAYOUT(
        KC_ESC , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,                   KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_BSPC,
        KC_TAB , KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   ,                   KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_DEL ,
        KC_LSFT, KC_H   , KC_J   , KC_K   , KC_L   , KC_G   ,                   KC_H   , C_MTRCJ, C_MTRSK, C_MTLAL, KC_SCLN, KC_QUOT, 
        KC_LCTL, KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, _______, KC_END , KC_N   , KC_M   , KC_COMM, KC_DOT,  KC_SLSH, TO(0), 
                                            KC_LGUI, KC_LALT, KC_ENT , KC_SPC , MO(3)  , KC_RALT
    ),
	[SYM] = LAYOUT(
        C_LSGR , S(KC_1), S(KC_2), S(KC_3), S(KC_4), S(KC_5),                   S(KC_6), S(KC_7), S(KC_8), S(KC_9), S(KC_0), KC_BSPC, 
        KC_GRV , _______, _______, _______, _______, _______,                   _______, KC_LCBR, KC_RCBR, KC_LBRC, KC_RBRC, KC_DEL, 
        _______, _______, KC_LALT, KC_LSFT, KC_LCTL, _______,                   _______, KC_RCTL, KC_RSFT, KC_LALT, KC_EQL , KC_BSLS,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_UNDS, KC_MINS, _______,
                                            _______, _______, _______, _______, _______, _______
    ),
	[NAV] = LAYOUT(
        KC_F12 , KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  ,                   KC_F6  , KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 ,
        _______, KC_NUM , KC_HOME, KC_UP  , KC_END , KC_PGUP,                   _______, _______, _______, _______, _______, EE_CLR , 
        _______, _______, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN,                   KC_MPRV, C_MTCMN, C_MTCVU, KC_LALT, _______, _______, 
        KC_MUTE, _______, _______, _______, _______, _______, _______, _______, KC_MSTP, KC_MPLY, KC_VOLD, _______, _______, _______, 
                                            _______, _______, _______, _______, _______, _______
    ),
	[NUM] = LAYOUT(
        _______, _______, _______, _______, _______, _______,                   _______, _______, _______, _______, _______, _______, 
        _______, _______, _______, _______, _______, _______,                   _______, _______, _______, _______, _______, _______, 
        _______, _______, _______, _______, _______, _______,                   _______, _______, _______, _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, TO(0)  , 
                                            _______, _______, _______, _______, _______, _______
    )
};

layer_state_t layer_state_set_user(layer_state_t state) {
   return update_tri_layer_state(state, SYM, NAV, _ADJUST);
}

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




