VIA_ENABLE = yes
LTO_ENABLE = yes
ENCODER_MAP_ENABLE = no
CONSOLE_ENABLE = no
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes
RGB_MATRIX_MAXIMUM_BRIGHTNESS = 115

SRC += oneshot.c
SRC += swapper.c
SRC += layout_common.c
