
VIA_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = no
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes
OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
CAPS_WORD_ENABLE = yes

CONVERT_TO=<target>

SRC += oneshot.c
SRC += swapper.c
